# Generated by Django 5.0.7 on 2024-07-15 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('correct_answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OMRSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='omr_sheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('final_image', models.ImageField(blank=True, null=True, upload_to='final_images/')),
                ('stacked_image', models.ImageField(blank=True, null=True, upload_to='stacked_images/')),
                ('omr_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omrapp.omrsheet')),
            ],
        ),
    ]
